name: Publish release

on:
  release:
    types: [published]
    target_commitish: master

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Set release name
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish artifact
        env:
          GITHUB_ACTOR: sulemanshakil
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # If we split on '/' and take the 3rd value,
        # we can get the release name.
        run: |
          ./gradlew -Pversion=${GITHUB_REF#refs/tags/} publish
